version: '3'
services:
  postgres:
    image: postgres:15-alpine
    container_name: lptracker-postgres
    restart: always
    environment:
      POSTGRES_USER: lpuser
      POSTGRES_PASSWORD: lppass
      POSTGRES_DB: lptracker
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
